FROM sequenceiq/hadoop-docker:2.6.0

ADD core-site.xml.template $HADOOP_PREFIX/etc/hadoop/core-site.xml.template
ADD core-site.xml $HADOOP_PREFIX/etc/hadoop/core-site.xml
ADD httpfs-env.sh $HADOOP_PREFIX/etc/hadoop/httpfs-env.sh
